### ISSUE TITLE
does not work?

### ISSUE THREAD

**Issue by ballII** [relikd/Darker#1]
macOS 10.10.5

I downloaded Darker_v1.0.tar.gz and unzipped it, and then double-clicked the unzipped Darker but nothing happened (i.e., did not appear in the top menu bar). How should I make it work? Thanks.

**Comment by relikd** [comment]
can you try to run the app from Terminal and see if it outputs some errors?

Open `Terminal.app` and run `﻿﻿﻿﻿~/Downloads/Darker.app/Contents/MacOS/Darker` (assuming that is the location of the Darker app)

**Comment by ballII** [comment]
Result:
`dyld: Library not loaded: @rpath/libswiftCore.dylib`
`  Referenced from: /Users/MyName/Downloads/Darker.app/Contents/MacOS/Darker`
`  Reason: image not found`
`Trace/BPT trap: 5`

**Comment by relikd** [comment]
I've updated the readme. Can you try again with installed Swift 5 standard library?

**Comment by ballII** [comment]
After installation of Swift 5, Darker works. Thanks.
